# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HOME.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Panel = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Panel.sizePolicy().hasHeightForWidth())
        self.Btn_Panel.setSizePolicy(sizePolicy)
        self.Btn_Panel.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;\n"
"font: 87 9pt \"Arial Black\";")
        self.Btn_Panel.setObjectName("Btn_Panel")
        self.verticalLayout_2.addWidget(self.Btn_Panel)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    font: 87 9pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    font: 87 9pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"font: 87 9pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setStyleSheet("background-color: rgb(220, 220, 0);")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.page_1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(872, 400))
        self.frame_4.setMaximumSize(QtCore.QSize(872, 600))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.regEdit = QtWidgets.QLineEdit(self.frame_4)
        self.regEdit.setGeometry(QtCore.QRect(180, 139, 241, 31))
        self.regEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.regEdit.setObjectName("regEdit")
        self.cardEdit = QtWidgets.QLineEdit(self.frame_4)
        self.cardEdit.setGeometry(QtCore.QRect(160, 189, 251, 31))
        self.cardEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.cardEdit.setObjectName("cardEdit")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 149, 161, 16))
        self.label.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(456, 139, 111, 20))
        self.label_2.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 199, 141, 16))
        self.label_3.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 239, 211, 16))
        self.label_4.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.dateEdit.setGeometry(QtCore.QRect(610, 250, 191, 31))
        self.dateEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 289, 111, 16))
        self.label_5.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(460, 190, 101, 20))
        self.label_6.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(470, 250, 131, 20))
        self.label_7.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.bookEdit = QtWidgets.QLineEdit(self.frame_4)
        self.bookEdit.setGeometry(QtCore.QRect(230, 229, 211, 31))
        self.bookEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.bookEdit.setObjectName("bookEdit")
        self.unitEdit = QtWidgets.QLineEdit(self.frame_4)
        self.unitEdit.setGeometry(QtCore.QRect(130, 279, 231, 31))
        self.unitEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.unitEdit.setObjectName("unitEdit")
        self.telEdit = QtWidgets.QLineEdit(self.frame_4)
        self.telEdit.setGeometry(QtCore.QRect(570, 139, 251, 31))
        self.telEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.telEdit.setObjectName("telEdit")
        self.courseEdit = QtWidgets.QLineEdit(self.frame_4)
        self.courseEdit.setGeometry(QtCore.QRect(570, 189, 251, 31))
        self.courseEdit.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.courseEdit.setObjectName("courseEdit")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(220, 90, 421, 31))
        self.label_8.setStyleSheet("font: 22pt \"MS Sans Serif\";\n"
"text-decoration: underline;\n"
"")
        self.label_8.setObjectName("label_8")
        self.submitButton = QtWidgets.QPushButton(self.frame_4)
        self.submitButton.setGeometry(QtCore.QRect(704, 350, 131, 41))
        self.submitButton.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.submitButton.setObjectName("submitButton")
        self.updateButton = QtWidgets.QPushButton(self.frame_4)
        self.updateButton.setGeometry(QtCore.QRect(40, 350, 131, 41))
        self.updateButton.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.updateButton.setObjectName("updateButton")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(220, 10, 421, 30))
        self.label_15.setMinimumSize(QtCore.QSize(421, 30))
        self.label_15.setMaximumSize(QtCore.QSize(421, 30))
        self.label_15.setStyleSheet("font: 14pt \"MS Sans Serif\";\n"
"color: rgb(198, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.confirmline = QtWidgets.QLineEdit(self.frame_4)
        self.confirmline.setGeometry(QtCore.QRect(20, 50, 181, 31))
        self.confirmline.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.confirmline.setObjectName("confirmline")
        self.confirmregistered = QtWidgets.QPushButton(self.frame_4)
        self.confirmregistered.setGeometry(QtCore.QRect(220, 50, 111, 31))
        self.confirmregistered.setMinimumSize(QtCore.QSize(111, 31))
        self.confirmregistered.setMaximumSize(QtCore.QSize(111, 31))
        self.confirmregistered.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.confirmregistered.setObjectName("confirmregistered")
        self.submitButton.raise_()
        self.regEdit.raise_()
        self.cardEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.dateEdit.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.bookEdit.raise_()
        self.unitEdit.raise_()
        self.telEdit.raise_()
        self.courseEdit.raise_()
        self.label_8.raise_()
        self.updateButton.raise_()
        self.label_15.raise_()
        self.confirmline.raise_()
        self.confirmregistered.raise_()
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_1)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.page_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(881, 320))
        self.frame_8.setMaximumSize(QtCore.QSize(900, 450))
        self.frame_8.setStyleSheet("background-color: transparent;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_circle_1 = QtWidgets.QFrame(self.frame_8)
        self.frame_circle_1.setGeometry(QtCore.QRect(50, 40, 250, 250))
        self.frame_circle_1.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_1.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_1.setStyleSheet("QFrame{\n"
"    \n"
"    border: 10px solid rgb(0, 136, 0);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_1.setObjectName("frame_circle_1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_circle_1)
        self.verticalLayout_10.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;\n"
"color: rgb(0, 136, 0);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.registered = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.registered.setFont(font)
        self.registered.setStyleSheet("border: none;\n"
"color: rgb(0, 136, 0);\n"
"font: 87 22pt \"Segoe UI Black\";")
        self.registered.setAlignment(QtCore.Qt.AlignCenter)
        self.registered.setObjectName("registered")
        self.verticalLayout_10.addWidget(self.registered)
        self.frame_circle_2 = QtWidgets.QFrame(self.frame_8)
        self.frame_circle_2.setGeometry(QtCore.QRect(320, 40, 250, 250))
        self.frame_circle_2.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_2.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_2.setStyleSheet("QFrame{\n"
"    border: 10px solid rgb(15, 99, 255);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(105, 95, 148);\n"
"}\n"
"    ")
        self.frame_circle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_2.setObjectName("frame_circle_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_circle_2)
        self.verticalLayout_11.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: none;\n"
"color: rgb(15, 99, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.attended = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.attended.setFont(font)
        self.attended.setStyleSheet("border: none;\n"
"color: rgb(15, 99, 255);\n"
"font: 87 22pt \"Segoe UI Black\";")
        self.attended.setAlignment(QtCore.Qt.AlignCenter)
        self.attended.setObjectName("attended")
        self.verticalLayout_11.addWidget(self.attended)
        self.frame_circle_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_circle_3.setGeometry(QtCore.QRect(610, 40, 250, 250))
        self.frame_circle_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_3.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_3.setStyleSheet("QFrame{\n"
"    border: 10px solid  rgb(255, 0, 0);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 10px solid rgb(105, 95, 148);\n"
"}\n"
"    color:;")
        self.frame_circle_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_3.setObjectName("frame_circle_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_circle_3)
        self.verticalLayout_12.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("border: none;\n"
"color: rgb(255, 0, 0);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_12.addWidget(self.label_25)
        self.unattended = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.unattended.setFont(font)
        self.unattended.setStyleSheet("border: none;\n"
"color:rgb(255, 0, 0);\n"
"font: 87 22pt \"Segoe UI Black\";")
        self.unattended.setAlignment(QtCore.Qt.AlignCenter)
        self.unattended.setObjectName("unattended")
        self.verticalLayout_12.addWidget(self.unattended)
        self.gridLayout_4.addWidget(self.frame_8, 3, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setMinimumSize(QtCore.QSize(321, 20))
        self.label_17.setMaximumSize(QtCore.QSize(321, 20))
        self.label_17.setStyleSheet("\n"
"font: 87 8pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.importCSV = QtWidgets.QPushButton(self.frame_7)
        self.importCSV.setMinimumSize(QtCore.QSize(121, 41))
        self.importCSV.setMaximumSize(QtCore.QSize(121, 41))
        self.importCSV.setStyleSheet("\n"
"QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.importCSV.setObjectName("importCSV")
        self.gridLayout_4.addWidget(self.importCSV, 1, 1, 2, 1)
        self.filename = QtWidgets.QLineEdit(self.frame_7)
        self.filename.setMinimumSize(QtCore.QSize(201, 31))
        self.filename.setMaximumSize(QtCore.QSize(201, 31))
        self.filename.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.filename.setObjectName("filename")
        self.gridLayout_4.addWidget(self.filename, 1, 0, 1, 1)
        self.sheetname = QtWidgets.QLineEdit(self.frame_7)
        self.sheetname.setMinimumSize(QtCore.QSize(181, 31))
        self.sheetname.setMaximumSize(QtCore.QSize(181, 31))
        self.sheetname.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.sheetname.setObjectName("sheetname")
        self.gridLayout_4.addWidget(self.sheetname, 2, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setMinimumSize(QtCore.QSize(892, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(791, 131))
        self.frame_5.setMaximumSize(QtCore.QSize(791, 131))
        self.frame_5.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(640, 10, 113, 16))
        self.label_12.setStyleSheet("\n"
"font: 87 8pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_12.setObjectName("label_12")
        self.linedelreg = QtWidgets.QLineEdit(self.frame_5)
        self.linedelreg.setGeometry(QtCore.QRect(620, 40, 144, 24))
        self.linedelreg.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.linedelreg.setObjectName("linedelreg")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(460, 40, 155, 16))
        self.label_9.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.deleteButton = QtWidgets.QPushButton(self.frame_5)
        self.deleteButton.setGeometry(QtCore.QRect(690, 70, 75, 23))
        self.deleteButton.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.deleteButton.setObjectName("deleteButton")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(122, 10, 151, 20))
        self.label_13.setStyleSheet("\n"
"font: 87 8pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.label_13.setObjectName("label_13")
        self.linereg = QtWidgets.QLineEdit(self.frame_5)
        self.linereg.setGeometry(QtCore.QRect(170, 40, 144, 24))
        self.linereg.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.linereg.setObjectName("linereg")
        self.searchreg = QtWidgets.QPushButton(self.frame_5)
        self.searchreg.setGeometry(QtCore.QRect(320, 40, 75, 23))
        self.searchreg.setStyleSheet("\n"
"QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.searchreg.setObjectName("searchreg")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 155, 16))
        self.label_11.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_11.setObjectName("label_11")
        self.lineexam = QtWidgets.QLineEdit(self.frame_5)
        self.lineexam.setGeometry(QtCore.QRect(170, 80, 144, 24))
        self.lineexam.setStyleSheet("border : 2px solid green;\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.lineexam.setObjectName("lineexam")
        self.searchunit = QtWidgets.QPushButton(self.frame_5)
        self.searchunit.setGeometry(QtCore.QRect(320, 80, 75, 23))
        self.searchunit.setStyleSheet("\n"
"QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.searchunit.setObjectName("searchunit")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(50, 80, 109, 16))
        self.label_10.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.label_10.setObjectName("label_10")
        self.refreshButton = QtWidgets.QPushButton(self.frame_5)
        self.refreshButton.setGeometry(QtCore.QRect(690, 100, 75, 31))
        self.refreshButton.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(872, 261))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 3)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMinimumSize(QtCore.QSize(791, 61))
        self.frame_6.setMaximumSize(QtCore.QSize(791, 61))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.exportCSV = QtWidgets.QPushButton(self.frame_6)
        self.exportCSV.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.exportCSV.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.exportCSV.setObjectName("exportCSV")
        self.exportPDF = QtWidgets.QPushButton(self.frame_6)
        self.exportPDF.setGeometry(QtCore.QRect(674, 20, 101, 31))
        self.exportPDF.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.exportPDF.setObjectName("exportPDF")
        self.refreshButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.refreshButton_2.setGeometry(QtCore.QRect(370, 20, 75, 31))
        self.refreshButton_2.setStyleSheet("QPushButton {\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(0, 134, 98);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.refreshButton_2.setObjectName("refreshButton_2")
        self.gridLayout_3.addWidget(self.frame_6, 2, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setMinimumSize(QtCore.QSize(400, 23))
        self.label_14.setMaximumSize(QtCore.QSize(450, 23))
        self.label_14.setStyleSheet("\n"
"font: 87 12pt \"Arial Black\";text-decoration: underline;\n"
"")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(872, 261))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 500))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.gridLayout_3.addWidget(self.tableWidget_2, 1, 0, 1, 2)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HOME"))
        self.Btn_Panel.setText(_translate("MainWindow", "PANEL"))
        self.btn_page_1.setText(_translate("MainWindow", "RECORD"))
        self.btn_page_2.setText(_translate("MainWindow", "VIEW"))
        self.btn_page_3.setText(_translate("MainWindow", "PRINT"))
        self.regEdit.setPlaceholderText(_translate("MainWindow", "      eg PS14/0000/10"))
        self.cardEdit.setPlaceholderText(_translate("MainWindow", "   1234-9*****"))
        self.label.setText(_translate("MainWindow", "REGISTRATION NUMBER:"))
        self.label_2.setText(_translate("MainWindow", "PHONE NUMBER:"))
        self.label_3.setText(_translate("MainWindow", "EXAM CARD NUMBER:"))
        self.label_4.setText(_translate("MainWindow", "EXAM BOOKLET SERIAL NUMBER:"))
        self.label_5.setText(_translate("MainWindow", "EXAM UNITCODE:"))
        self.label_6.setText(_translate("MainWindow", "COURSE NAME:"))
        self.label_7.setText(_translate("MainWindow", "EXAMINATION DATE:"))
        self.bookEdit.setPlaceholderText(_translate("MainWindow", " 0******"))
        self.unitEdit.setPlaceholderText(_translate("MainWindow", "   eg SOEN 411"))
        self.telEdit.setPlaceholderText(_translate("MainWindow", "                    07***********"))
        self.courseEdit.setPlaceholderText(_translate("MainWindow", "   eg computer science"))
        self.label_8.setText(_translate("MainWindow", "EXAMINATION FORM SYSTEM"))
        self.submitButton.setText(_translate("MainWindow", "SUBMIT"))
        self.updateButton.setText(_translate("MainWindow", "UPDATE"))
        self.label_15.setText(_translate("MainWindow", "*The student must be registered to do an exam"))
        self.confirmline.setPlaceholderText(_translate("MainWindow", "Registration Number"))
        self.confirmregistered.setText(_translate("MainWindow", "CONFIRM"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">REGISTERED</span></p></body></html>"))
        self.registered.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ATTENDANCE</span></p></body></html>"))
        self.attended.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">UNATTENDED</span></p></body></html>"))
        self.unattended.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", " IMPORT EXCEL FILE WITH REGISTERED STUDENTS "))
        self.importCSV.setText(_translate("MainWindow", "IMPORT"))
        self.sheetname.setPlaceholderText(_translate("MainWindow", "   sheet name"))
        self.label_12.setText(_translate("MainWindow", "DELETE RECORDS"))
        self.label_9.setText(_translate("MainWindow", "REGISTRATION NUMBER:"))
        self.deleteButton.setText(_translate("MainWindow", "DELETE"))
        self.label_13.setText(_translate("MainWindow", "SEARCH RECORDS BY:"))
        self.searchreg.setText(_translate("MainWindow", "SEARCH"))
        self.label_11.setText(_translate("MainWindow", "REGISTRATION NUMBER:"))
        self.searchunit.setText(_translate("MainWindow", "SEARCH"))
        self.label_10.setText(_translate("MainWindow", "EXAM UNITCODE:"))
        self.refreshButton.setText(_translate("MainWindow", "REFRESH"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Registration Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Examcard Number"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Booklet Number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Exam unitcode"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Phone number"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Examination Date"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Course Name"))
        self.exportCSV.setText(_translate("MainWindow", "EXPORT CSV"))
        self.exportPDF.setText(_translate("MainWindow", "EXPORT PDF"))
        self.refreshButton_2.setText(_translate("MainWindow", "REFRESH"))
        self.label_14.setText(_translate("MainWindow", "REVIEW RECORDS AND PRINT REPORT"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Registration Number"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Examcard Number"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Booklet Number"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Exam unitcode"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Phone number"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Examination Date"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Course Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
